project:
  type: website

website:
  page-navigation: true
  title: "Luke Pembleton"
  open-graph: true
  twitter-card: 
    site: "@lwpembleton"
  navbar:
    right:
      - text: About
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - text: Publications
        href: publications/publications.qmd
      - text: Conferences
        href: pages/conferences.qmd
      - icon: github
        href: https://github.com/lpembleton
      - icon: twitter
        href: https://twitter.com/lwpembleton
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?user=r7RmM00AAAAJ&hl=en
      - text: "{{< ai publons >}}"
        href: https://publons.com/researcher/3450394/luke-pembleton/
      - icon: linkedin
        href: https://linkedin.com/in/lpembleton
      - text: "{{< fa solid box-open >}}"
        href: https://lpembleton.github.io/StAMPP/
format:
  html:
    theme: 
    - litera
    - theme.scss

editor: visual
