project:
  type: website

website:
  title: "Luke W Pembleton"
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Blog
        href: index.qmd
      - text: Publications
        href: publications/publications.qmd
      - icon: github
        href: https://github.com/lpembleton
      - icon: twitter
        href: https://twitter.com/lwpembleton
      - text: Scholar
        href: https://scholar.google.com/citations?user=r7RmM00AAAAJ&hl=en
      - text: Publons
        href: https://publons.com/researcher/3450394/luke-pembleton/
      - icon: linkedin
        href: https://linkedin.com/in/lpembleton
format:
  html:
    theme: 
    - litera
    - theme.scss

editor: visual

